[theme]
base="dark"
primaryColor="#e06dbaff"             # couleur des boutons et éléments actifs
backgroundColor="#333030ff"          # fond principal
secondaryBackgroundColor="#1a1616c5" # fond des boîtes/sidebars
textColor="#FFFFFF"                # couleur du texte
